travis:
  secure:
    BINSTAR_TOKEN: pG9MxtdQBHLhOZgTkE6PTMDEzw1yxe7uf4sRrskSGkQn71pXl52p9At2YRPe+TaBBtlHg4uCHtowM3vNYzY8QwXvENg+6y7fqsnEX6vJ8/LIbkqn8vNFkXBfoiw64l7oi5x/BBpN/vXXV8uaO0ufSgGNbYQ+dVY04LZxqG0Q0WjnqCB7KcKXAABfCrpIQ/mXylc1fWxtUgPojCEMr+gUOeM36KYpApfEmaQJiIGsUVbgjjL2xs44bVbQeMqlrEDYVN3BVSWK2XMxcOiLYKKIr0zkWqNbxsYEJzroo5S8e4QF22boTm+J/NUMDCxcEnAVaS36sP56+eLLd0saGKvbJ4jvWOfLqeUYJpUmqHL+YajqRPLNyS/euCqAw0LLRxZCmKXeq40bGq7uqDY8kGCTJFxvNCJaYHbb1vRigGNZTgooeLLcoFZUzjZJ+9OWr6CQ9bhNYV4yFgRqjgx3ey6+wmq2cqrCfyq+9tfqlI2zsePe3H8PQIhSs3oibSEP5bMVNr01TFMexgOTyrkkQNaLz5F1vYKEKXwdd0qP/nQD692DUzkNqnrU4xJWMD+GxVy5huJyBqQAeXjZtlENRdtHIdOK7GrHCaKydeoXyg/N2H8ZLB7PWi/vX27u4G0fIRuU/uA4LneP5QOhdmzIk8MCRhhHQFDUlVGSSTW6iEu0gXo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
